// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    Carousel: typeof import('./src/components/carousel.vue')['default']
    copy: typeof import('./src/components/main/Main copy.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    Main: typeof import('./src/components/main/Main.vue')['default']
    MainTop: typeof import('./src/components/main/MainTop.vue')['default']
    Music: typeof import('./src/components/music/music.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Topbar: typeof import('./src/components/topbar/Topbar.vue')['default']
    Topright: typeof import('./src/components/topbar/Topright.vue')['default']
  }
}
